version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    funlen:
      lines: 75
      statements: 50
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 132
    revive:
      rules:
        - name: exported
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
