name: ci

on:
  push:
    branches:
      - 'releases/**'
      - 'feature/**'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o ssm-session-client .
        shell: bash

      - name: Run tests
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
        shell: bash

      - name: Display coverage
        run: go tool cover -func=coverage.out
        shell: bash

